version: '2'
services:
    bot:
        build: .
        environment:
          PYTHONUNBUFFERED: 1
          DEBUG: 'True'
          PROXY: 'socks5h://173.248.156.213:31648' #https://50na50.net/ru/proxy/socks5list
          DB_URI: "mysql+mysqldb://root:root@db:3306/bot_db?use_unicode=1&charset=utf8mb4"
          BOT_TOKEN: '1205108650:AAFLE6D3iQDuP3IneF7fwsMMm4jxCgm0ts0'
        depends_on:
          - db
        volumes:
          - ./:/code
        command: ["python", "chat_bot/main.py"]
        restart: always

    admin:
        build: .
        environment:
            DEBUG: 'True'
            DB_URI: "mysql+mysqldb://root:root@db:3306/bot_db?use_unicode=1&charset=utf8mb4"
        depends_on:
            - db
        volumes:
            - ./:/code
        ports:
            - 5000:5000
        restart: on-failure
        command: ["python", "admin/app.py"]

    db:
        build:
            context: .
            dockerfile: Dockerfile-DB
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "32000:3306"

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
